//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIActivityPanel
    {
        
        public const string NAME = "UIActivityPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Image ImagePanel;
        
        [SerializeField()]
        public UnityEngine.UI.Dropdown ActivityOptions;
        
        [SerializeField()]
        public UnityEngine.UI.Button Update;
        
        [SerializeField()]
        public UnityEngine.UI.Button Guide;
        
        [SerializeField()]
        public UnityEngine.UI.Button Start;
        
        private UIActivityPanelData mPrivateData = null;
        
        public UIActivityPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIActivityPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            ImagePanel = null;
            ActivityOptions = null;
            Update = null;
            Guide = null;
            Start = null;
            mData = null;
        }
    }
}
