//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIAddActivityPanel
    {
        
        public const string NAME = "UIAddActivityPanel";
        
        [SerializeField()]
        public UnityEngine.UI.InputField InputFieldConfig;
        
        [SerializeField()]
        public UnityEngine.UI.InputField InputFieldDesc;
        
        [SerializeField()]
        public UnityEngine.UI.Button Text;
        
        [SerializeField()]
        public UnityEngine.UI.Button Check;
        
        [SerializeField()]
        public UnityEngine.UI.Button Submit;
        
        [SerializeField()]
        public UnityEngine.UI.InputField InputFieldActivityIndex;
        
        private UIAddActivityPanelData mPrivateData = null;
        
        public UIAddActivityPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIAddActivityPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            InputFieldConfig = null;
            InputFieldDesc = null;
            Text = null;
            Check = null;
            Submit = null;
            InputFieldActivityIndex = null;
            mData = null;
        }
    }
}
