//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UILoginPanel
    {
        
        public const string NAME = "UILoginPanel";
        
        [SerializeField()]
        public UnityEngine.UI.InputField Mobile;
        
        [SerializeField()]
        public UnityEngine.UI.InputField Passwd;
        
        [SerializeField()]
        public UnityEngine.UI.InputField Google;
        
        [SerializeField()]
        public UnityEngine.UI.Button Login;
        
        private UILoginPanelData mPrivateData = null;
        
        public UILoginPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UILoginPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            Mobile = null;
            Passwd = null;
            Google = null;
            Login = null;
            mData = null;
        }
    }
}
