//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIPropertiesPanel
    {
        
        public const string NAME = "UIPropertiesPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button btn;
        
        [SerializeField()]
        public UnityEngine.UI.Button btnClose;
        
        private UIPropertiesPanelData mPrivateData = null;
        
        public UIPropertiesPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIPropertiesPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            btn = null;
            btnClose = null;
            mData = null;
        }
    }
}
