//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIResourcePanel
    {
        
        public const string NAME = "UIResourcePanel";
        
        [SerializeField()]
        public UnityEngine.UI.Text TextLabel;
        
        [SerializeField()]
        public UnityEngine.UI.Text Text;
        
        [SerializeField()]
        public UnityEngine.UI.Toggle ToggleTexturePackage;
        
        [SerializeField()]
        public UnityEngine.UI.Toggle ToggleGenerateCode;
        
        [SerializeField()]
        public UnityEngine.UI.Toggle ToggleCompress;
        
        [SerializeField()]
        public UnityEngine.UI.Button Export;
        
        [SerializeField()]
        public UnityEngine.UI.Button Clear;
        
        [SerializeField()]
        public UnityEngine.UI.Button God;
        
        private UIResourcePanelData mPrivateData = null;
        
        public UIResourcePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIResourcePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            TextLabel = null;
            Text = null;
            ToggleTexturePackage = null;
            ToggleGenerateCode = null;
            ToggleCompress = null;
            Export = null;
            Clear = null;
            God = null;
            mData = null;
        }
    }
}
