//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIUploadPanel
    {
        
        public const string NAME = "UIUploadPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Image ItemIdDropdown;
        
        [SerializeField()]
        public UnityEngine.UI.Button Query;
        
        [SerializeField()]
        public UnityEngine.UI.Button Home;
        
        [SerializeField()]
        public UnityEngine.UI.Text ActivityText;
        
        private UIUploadPanelData mPrivateData = null;
        
        public UIUploadPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIUploadPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            ItemIdDropdown = null;
            Query = null;
            Home = null;
            ActivityText = null;
            mData = null;
        }
    }
}
