//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using NRatel.TextureUnpacker;
    using QF.Master;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Text;
    using UnityEngine;
    using UnityEngine.Networking;
    using UnityEngine.UI;

    public class SetBlockProperties
    {
        public string MD5;
        public Dictionary<string, string> properties;
    }

    public class ClearRescoursePanel
    {

    }
    
    public class UIUploadPanelData : QFramework.UIPanelData
    {
        public string ActivityIndex;
        public string id;
    }
    
    public partial class UIUploadPanel : QFramework.UIPanel
    {

        private string Auth = "****";
        private string ActivityIndex = "**";

        private string ItemId;

        public GameObject AttachmentPrefab;
        public Transform Content;

        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UIUploadPanelData ?? new UIUploadPanelData();
            // please add init code here
            ActivityIndex = mData.ActivityIndex.ToLower();
            
            Query.onClick.AddListener(() =>
            {
                var lst = new List<Transform>();
                foreach (Transform child in Content)
                {
                    lst.Add(child);
                }
                for (int i = 0; i < lst.Count; i++)
                {
                    Destroy(lst[i].gameObject);

                }
                var str = ItemIdDropdown.GetComponent<Dropdown>().captionText.text;
                if (str.IndexOf("SkinName") > -1)
                {
                    ItemId = str.Split('|')[1].Split(':')[1];
                    StartCoroutine(GetAttachments("Skin", ItemId));
                }

            });
            Home.onClick.AddListener(() =>
            {
                UIMgr.ClosePanel("UIUploadPanel");
            });
            Auth = PlayerPrefs.GetString("access_token");
            StartCoroutine(GetItemId(int.Parse(mData.id)));
            ActivityText.text = ActivityIndex;
        }

        IEnumerator GetAttachments(string itemType, string itemId)
        {
            var url = string.Format("https://gate.mongomath.com:8443/admin-course/item/attachment?itemType={0}&itemId={1}", itemType, itemId);
            UnityWebRequest webRequest = UnityWebRequest.Get(url);
            webRequest.SetRequestHeader("Authorization", Auth);
            webRequest.SetRequestHeader("Content-Type", "application/json");
            yield return webRequest.SendWebRequest();

            if (webRequest.isNetworkError)
            {
                Debug.Log(": Error: " + webRequest.error);
            }
            else
            {
                Debug.Log(webRequest.downloadHandler.text);
                var list = QF.SerializeHelper.FromJson<List<AttachmentsConfig>>(webRequest.downloadHandler.text);
                list.ForEach((item) =>
                {
                    item.itemId = itemId;
                    StartCoroutine(initAttachment(item));
                });
            }
        }

        IEnumerator initAttachment(AttachmentsConfig config)
        {
            var obj = Instantiate(AttachmentPrefab, Content);
            obj.transform.Find("Name").GetComponent<Text>().text = "资源名称: " + config.name;
            var uri = "";
            if (config.attachments.uri.IndexOf(".zip") > -1)
            {
                uri = "https://s2.ax1x.com/2019/10/09/u50uEn.png";
            }
            else
            {
                uri = "https://s2.ax1x.com/2019/10/09/u5DlXF.png";
            }
            WWW www = new WWW(uri);//��WWW��������ͼƬ
            yield return www;
            var image = obj.transform.Find("Image").GetComponent<Image>();
            if (www != null && string.IsNullOrEmpty(www.error))
            {
                //��ȡTexture
                Texture2D texture = www.texture;
                //��Ϊ���Ƕ������Image������������Ҫ��Texture2Dת��ΪSprite
                Sprite sprite = Sprite.Create(texture, new Rect(0, 0, texture.width, texture.height), new Vector2(0.5f, 0.5f));
                image.sprite = sprite;
            }
            var btn_repleace = obj.transform.Find("Replace").GetComponent<Button>();
            btn_repleace.onClick.AddListener(() =>
            {
                StartCoroutine(BackupConfig(config, "replace"));
            });
            var btn_download = obj.transform.Find("Download").GetComponent<Button>();
            btn_download.onClick.AddListener(() =>
            {
                //var url = string.Format("http://gate-static.97kid.com/{0}", config.attachments.uri);
                //Application.OpenURL(url);
                StartCoroutine(GetArgu("Skin", ItemId));
            });

            var btn_restore = obj.transform.Find("Restore").GetComponent<Button>();
            btn_restore.onClick.AddListener(() =>
            {
                StartCoroutine(BackupConfig(config, "restore"));
            });
        }



        IEnumerator GetItemId(int template_id)
        {
            var url = string.Format("https://gate.mongomath.com:8443/admin-course/skin?templateId={0}", template_id);
            UnityWebRequest webRequest = UnityWebRequest.Get(url);
            webRequest.SetRequestHeader("Authorization", Auth);
            webRequest.SetRequestHeader("Content-Type", "application/json");
            yield return webRequest.SendWebRequest();
            if (webRequest.isNetworkError)
            {
                Debug.Log(": Error: " + webRequest.error);
            }
            else
            {
                ItemIdDropdown.GetComponent<Dropdown>().ClearOptions();
                Debug.Log(webRequest.downloadHandler.text);
                var skinsConfig = QF.SerializeHelper.FromJson<List<Assets.Scripts.Upload.SkinsConfig>>(webRequest.downloadHandler.text);
                var options = skinsConfig.Select((data, index) =>
                {
                    var str = string.Format((index+1)+" SkinName:{1}-SkinId:{2} | ItemId:{0}", data.id, data.name, data.skin_id);
                    return str;
                }).ToList();
                ItemIdDropdown.GetComponent<Dropdown>().AddOptions(new List<string>()
                {
                    "选择Skin"
                });
                ItemIdDropdown.GetComponent<Dropdown>().AddOptions(options);
                ItemIdDropdown.GetComponent<Dropdown>().AddOptions(new List<string>()
                {
                    ""
                });
            }
        }

        IEnumerator BackupConfig(AttachmentsConfig config, string type)
        {
            var url = string.Format("http://gate-static.97kid.com/{0}", config.attachments.uri);
            UnityWebRequest webRequest = UnityWebRequest.Get(url);
            yield return webRequest.SendWebRequest();
            if (webRequest.isNetworkError)
            {
                Debug.Log(": Error: " + webRequest.error);
            }
            else
            {
                DateTime date = DateTime.Now;
                var dateStr = date.ToString("yyyyMMdd-HH时mm分ss秒");
                var zipPath = DirTools.GetBackupDir()+"/"+dateStr+ "."+ config.attachments.ext_name;
                Debug.Log(zipPath);
                var data = webRequest.downloadHandler.data;
                File.WriteAllBytes(zipPath, data);
                if(type == "replace")
                {
                    StartCoroutine(UploadConfig(config));
                }
                else if(type == "restore")
                {
                    DirTools.DeleteFolder(DirTools.GetUnZipDir());
                    ZipUtil.UnZipFile(zipPath, DirTools.GetUnZipDir());
                    StartCoroutine(Unpacker(DirTools.GetUnZipDir() + "/default.plist", DirTools.GetUnZipDir() + "/default.png"));
                }
                
            }
        }

        public Dictionary<string, string> GetDescription()
        {
            var description_dict = new Dictionary<string, string>();
            var dict = getResConfig(DirTools.GetTmpOutPutDir());
            foreach (KeyValuePair<string, Dictionary<string, string>> kv in dict)
            {
                var properties = kv.Value;
                string description;
                properties.TryGetValue("Description", out description);
                if(description == null || description == "")
                {
                    Debug.Log("properties:"+properties["Name"]);
                }
                else
                {
                    description_dict.Add(kv.Key, description);
                }
            }
            Debug.Log(description_dict.ToString());
            return description_dict;
        }

        IEnumerator GetArgu(string itemType, string itemId)
        {
            
            var exsitArgu = new Dictionary<string, string>();
            var url = string.Format("https://gate.mongomath.com:8443/admin-course/properties?itemType={0}&itemId={1}", itemType, itemId);
            UnityWebRequest webRequest = UnityWebRequest.Get(url);
            webRequest.SetRequestHeader("Authorization", Auth);
            webRequest.SetRequestHeader("Content-Type", "application/json");
            yield return webRequest.SendWebRequest();

            if (webRequest.isNetworkError)
            {
                Debug.Log(": Error: " + webRequest.error);
            }
            else
            {
                Debug.LogWarning(webRequest.downloadHandler.text);
                var description_dict = GetDescription();
                var list = QF.SerializeHelper.FromJson<List<PropertiesConfig>>(webRequest.downloadHandler.text);


                foreach (KeyValuePair<string, string> kv in description_dict)
                {
                    Debug.Log(string.Format("key:{0}-value{1}", kv.Key, kv.Value));
                    var ret = list.Find((tmp) =>
                    {
                        return kv.Key == tmp.name;
                    });
                    if (ret != null)
                    {
                        if (ret.content == kv.Value)
                        {
                            Debug.Log("一致的内容不更新" + kv.Key);
                        }
                        else
                        {
                            Debug.Log("更新" + kv.Key+"id"+ ret.id);
                            StartCoroutine(UpdateArgu(itemType, itemId, kv.Key, kv.Value, ret.id + ""));
                        }
                    }
                    else
                    {
                        StartCoroutine(UploadArgu(itemType, itemId, kv.Key, kv.Value));
                    }
                }
            }
        }



        IEnumerator UploadArgu(string itemType, string itemId, string name, string content)
        {
            var url = string.Format("https://gate.mongomath.com:8443/admin-course/properties");
            WWWForm form = new WWWForm();
            form.AddField("itemType", itemType);
            form.AddField("itemId", itemId);
            form.AddField("name", name);
            form.AddField("content", content);
            UnityWebRequest webRequest = UnityWebRequest.Post(url, form);
            webRequest.SetRequestHeader("Authorization", Auth);
            yield return webRequest.SendWebRequest();

            if (webRequest.isNetworkError)
            {
                Debug.Log(": Error: " + webRequest.error);
            }
            else
            {
                Debug.LogWarning(webRequest.downloadHandler.text);
                MessageBoxV2.AddMessage("上传字段" + name);
            }
        }

        IEnumerator UpdateArgu(string itemType, string itemId, string name, string content, string id)
        {
            Debug.Log("UpdateArgu");
            var dict = new Dictionary<string, string>();
            dict["id"] = id;
            dict["itemType"] = itemType;
            dict["itemId"] = itemId;
            dict["name"] = name;
            dict["content"] = content;
            var argu = QF.SerializeHelper.ToJson<Dictionary<string, string>>(dict);
            var webRequest = UnityWebRequest.Put("https://gate.mongomath.com:8443/admin-course/properties/" + id, argu);
            webRequest.SetRequestHeader("Authorization", Auth);
            webRequest.SetRequestHeader("Content-Type", "application/json");
            yield return webRequest.SendWebRequest();
            if (webRequest.isNetworkError)
            {
                Debug.Log(": Error: " + webRequest.error);
            }
            else
            {
                Debug.Log(webRequest.downloadHandler.text);
                MessageBoxV2.AddMessage("更新字段" + name);
            }
        }


        IEnumerator Unpacker(string plistFilePath, string pngFilePath)
        {
            DirTools.DeleteFolder(DirTools.GetRestoredPNGDir());
            var loader = NRatel.TextureUnpacker.Loader.LookingForLoader(plistFilePath);
            if (loader != null)
            {
                var plist = loader.LoadPlist(plistFilePath);
                var bigTexture = loader.LoadTexture(pngFilePath, plist.metadata);

                int total = plist.frames.Count;
                int count = 0;
                foreach (var frame in plist.frames)
                {
                    try
                    {
                        Core.Restore(bigTexture, frame);
                        count += 1;
                    }
                    catch
                    {
                    }
                }
            }
            DirectoryInfo dir = new DirectoryInfo(DirTools.GetUnZipDir());
            FileInfo[] finfo = dir.GetFiles();
            for (int i = 0; i < finfo.Length; i++)
            {
                var file = finfo[i];
                if (file.Name.IndexOf("plist") > -1 || file.Name.IndexOf("png") > -1)
                {

                }
                else
                {
                    File.Copy(file.FullName, DirTools.GetRestoredPNGDir()+"/"+ file.Name, true);
                }
            }
            ImportToResPanel();
            yield return null;
        }

        public Dictionary<string, Dictionary<string, string>> getResConfig(string path)
        {
            StreamReader sr = new StreamReader(path + "/ResConfig.json");
            if (sr == null)
            {
                return null;
            }
            string json = sr.ReadToEnd();
            sr.Close();
            var dict = QF.SerializeHelper.FromJson<Dictionary<string, Dictionary<string, string>>>(json);
            return dict;
        }

        public void ImportToResPanel()
        {
            TypeEventSystem.Send(new ClearRescoursePanel());
            var dict = getResConfig(DirTools.GetRestoredPNGDir());
            foreach (KeyValuePair<string, Dictionary<string, string>> kv in dict)
            {
                var properties = kv.Value;
                var Name = properties["Name"];
                var MD5 = properties["MD5"];
                var Extension = properties["Extension"];
                var fileinfo = new FilePathInfo()
                {
                    FilePath = DirTools.GetRestoredPNGDir()+"/"+MD5+ Extension,
                    FileName = Name + Extension,
                    Extension = Extension,
                    MD5 = MD5
                };
                TypeEventSystem.Send(fileinfo);
                TypeEventSystem.Send(new SetBlockProperties()
                {
                    MD5 = MD5,
                    properties = properties
                });
            }
            UIMgr.ClosePanel("UIUploadPanel");

        }

        IEnumerator UploadConfig(AttachmentsConfig config)
        {


            var filePath = DirTools.GetOutPutDir() + "/ResConfig.zip";
            if (!File.Exists(filePath))
            {
                MessageBoxV2.AddMessage("请先导出资源！");
                yield return null;
            }
            else
            {
                FileStream fs = new FileStream(filePath, FileMode.Open, FileAccess.Read);
                byte[] bytes = new byte[fs.Length];
                fs.Read(bytes, 0, (int)fs.Length);
                WWWForm form = new WWWForm();
                form.AddBinaryData("file", bytes, "ResConfig.zip");
                var webRequest = UnityWebRequest.Post("https://gate.mongomath.com:8443/admin-course/asset/uploadSingle", form);
                webRequest.SetRequestHeader("Authorization", Auth);
                //webRequest.SetRequestHeader("Content-Type", "application/x-www-form-urlencoded");
                yield return webRequest.SendWebRequest();
                if (webRequest.isNetworkError)
                {
                    Debug.Log(": Error: " + webRequest.error);
                }
                else
                {
                    Debug.Log(webRequest.downloadHandler.text);
                    var dict = QF.SerializeHelper.FromJson<Dictionary<string, string>>(webRequest.downloadHandler.text);
                    var attachment_id = dict["id"];
                    Debug.Log("上传成功" + attachment_id);
                    StartCoroutine(UpdateAttachment(config, attachment_id));
                }
            }

        }

        IEnumerator UpdateAttachment(AttachmentsConfig config, string attachment_id)
        {
            var dict = new Dictionary<string, string>();
            dict["id"] = config.id+"";
            dict["itemType"] = "Skin";
            dict["itemId"] = config.itemId;
            dict["name"] = config.name;
            dict["attachmentId"] = attachment_id;
            var argu = QF.SerializeHelper.ToJson<Dictionary<string, string>>(dict);
            var webRequest = UnityWebRequest.Put("https://gate.mongomath.com:8443/admin-course/item/attachment/"+ config.id, argu);
            webRequest.SetRequestHeader("Authorization", Auth);
            webRequest.SetRequestHeader("Content-Type", "application/json");
            yield return webRequest.SendWebRequest();
            if (webRequest.isNetworkError)
            {
                Debug.Log(": Error: " + webRequest.error);
            }
            else
            {
                Debug.Log(webRequest.downloadHandler.text);
                var ret = QF.SerializeHelper.FromJson<Dictionary<string, bool>>(webRequest.downloadHandler.text);
                var isSuccess = ret["updated"];
                if (isSuccess)
                {
                    MessageBoxV2.AddMessage("更新资源成功",4);
                    StartCoroutine(GetArgu("Skin", config.itemId));
                }
            }
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
